[0m10:23:19.090592 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BA9449A00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BA5C32780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BA8ADD400>]}


============================== 10:23:19.096098 | a7ccac07-a14a-416e-bd60-b90d5f3cc103 ==============================
[0m10:23:19.096098 [info ] [MainThread]: Running with dbt=1.10.6
[0m10:23:19.096098 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\anvm1\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'invocation_command': 'dbt init insurance_dbt', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:23:19.120591 [debug] [MainThread]: Starter project path: C:\Users\anvm1\anaconda3\Lib\site-packages\dbt\include\starter_project
[0m10:23:19.129206 [info ] [MainThread]: 
Your new dbt project "insurance_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:23:19.129206 [info ] [MainThread]: Setting up your profile.
[0m10:26:24.948312 [debug] [MainThread]: Command `dbt init` succeeded at 10:26:24.948312 after 185.95 seconds
[0m10:26:24.948312 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BA8D030B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BAAB036E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014BAAA25820>]}
[0m10:26:24.948312 [debug] [MainThread]: Flushing usage events
[0m10:26:25.287919 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:53:11.811204 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C2660BF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C2666E720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C2666D9A0>]}


============================== 13:53:11.815223 | 34ec88dc-800d-4011-a233-8ba08d7d2b22 ==============================
[0m13:53:11.815223 [info ] [MainThread]: Running with dbt=1.10.9
[0m13:53:11.815223 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'profiles_dir': 'C:\\Users\\anvm1\\.dbt', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt debug', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'empty': 'None', 'use_experimental_parser': 'False', 'quiet': 'False', 'log_cache_events': 'False', 'log_path': 'logs', 'indirect_selection': 'eager', 'write_json': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m13:53:11.824532 [info ] [MainThread]: dbt version: 1.10.9
[0m13:53:11.824532 [info ] [MainThread]: python version: 3.12.7
[0m13:53:11.825533 [info ] [MainThread]: python path: C:\Users\anvm1\OneDrive\Desktop\Andrew_Vu\Projects\insurance_data\insurance_data\.venv\Scripts\python.exe
[0m13:53:11.825533 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m13:53:11.829497 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.bigquery'
[0m13:53:11.894820 [info ] [MainThread]: Using profiles dir at C:\Users\anvm1\.dbt
[0m13:53:11.894820 [info ] [MainThread]: Using profiles.yml file at C:\Users\anvm1\.dbt\profiles.yml
[0m13:53:11.894820 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\anvm1\OneDrive\Desktop\Andrew_Vu\Projects\insurance_data\insurance_data\dbt_project.yml
[0m13:53:11.895822 [info ] [MainThread]: Configuration:
[0m13:53:11.895822 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m13:53:11.895822 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:53:11.895822 [info ] [MainThread]: Required dependencies:
[0m13:53:11.895822 [debug] [MainThread]: Executing "git --help"
[0m13:53:11.919703 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m13:53:11.919703 [debug] [MainThread]: STDERR: "b''"
[0m13:53:11.919703 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m13:53:11.919703 [info ] [MainThread]: Connection test skipped since no profile was found
[0m13:53:11.920965 [info ] [MainThread]: [31m2 checks failed:[0m
[0m13:53:11.920965 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "dbt_project", target "dev" invalid: Runtime Error
    Could not find adapter type bigquery!


[0m13:53:11.920965 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\anvm1\OneDrive\Desktop\Andrew_Vu\Projects\insurance_data\insurance_data\dbt_project.yml> not found

[0m13:53:11.922015 [debug] [MainThread]: Command `dbt debug` failed at 13:53:11.922015 after 0.19 seconds
[0m13:53:11.922015 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C2663E810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C2663F8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015C2663D4C0>]}
[0m13:53:11.922015 [debug] [MainThread]: Flushing usage events
[0m13:53:12.372098 [debug] [MainThread]: An error was encountered while trying to flush usage events
